spring.application.name=FestApp

# MySQL Database Connection

#spring.datasource.url=jdbc:mysql://localhost:3306/festdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=tiger


#aiven db connection - #jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#jdbc:mysql://mysql-502b3a8-dhanunjay918-7c88.g.aivencloud.com:21563/defaultdb
#spring.datasource.username=avnadmin


spring.datasource.url=jdbc:mysql://mysql-502b3a8-dhanunjay918-7c88.g.aivencloud.com:21563/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

